# Generated by Django 5.0.2 on 2024-08-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_livro_nome_livro_isbn_livro_preco_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="titulo",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
